### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #8

Adds all dependency build in the project, thereby not requiring any dependencies from the user other than CMake and a C++11 compliant compiler.

Needs testing on whatever platform this project was built last. ~I tried compiling on CentOS7 but failed [[ref](https://github.com/keroro824/HashingDeepLearning/issues/8#issuecomment-594918601)].~ Update: fixed with [this include](https://github.com/keroro824/HashingDeepLearning/issues/8#issuecomment-596107068).

Looking forward to doing some amazing work with this!

Cheers,
Sarthak

### CODE REVIEW

**Comment by rahulunair** [comment]
I can try building on Arch linux , Skylake i9 in sometime.

**Comment by sarthakpati** [comment]
Compiling on WSL:

```bash
root@pc:/mnt/c/Testing# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
[SNIP!]
root@pc:/mnt/c/Projects/HashingDeepLearning/bin_linux# ls -l
total 1344
-rwxrwxrwx 1 root root  13934 Mar  4 22:31 CMakeCache.txt
drwxrwxrwx 1 root root   4096 Mar  4 22:32 CMakeFiles
-rwxrwxrwx 1 root root   2673 Mar  4 22:31 cmake_install.cmake
drwxrwxrwx 1 root root   4096 Mar  4 22:26 CNPY-build
drwxrwxrwx 1 root root   4096 Mar  4 22:25 CNPY-prefix
drwxrwxrwx 1 root root   4096 Mar  4 22:26 CNPY-source
drwxrwxrwx 1 root root   4096 Mar  4 22:26 ep
-rwxrwxrwx 1 root root 750128 Mar  4 22:26 libSLIDE_LIB.a
-rwxrwxrwx 1 root root  16972 Mar  4 22:32 Makefile
-rwxrwxrwx 1 root root 579336 Mar  4 22:32 runme
drwxrwxrwx 1 root root   4096 Mar  4 22:26 ZLIB-build
drwxrwxrwx 1 root root   4096 Mar  4 22:25 ZLIB-prefix
drwxrwxrwx 1 root root   4096 Mar  4 22:26 ZLIB-source
```

The CMake port works!

**Review by rahulunair — APPROVED** [review]
Nice work !

**Comment by rahulunair** [comment]
May be rebase and update the PR?

**Comment by sarthakpati** [comment]
@rahulunair: Done!

**Comment by sarthakpati** [comment]
Hey @keroro824, could you give me an estimate on when this can be merged? 

Cheers.

**Comment by Tharun24** [comment]
Hey @sarthakpati , we trained with your changes but the code was super slow apparently bcz you didn't enable OpenMP. Can you fix that and push your commits?

**Comment by sarthakpati** [comment]
@Tharun24: done!

**Comment by sarthakpati** [comment]
Hello, any updates on the merge status?

**Comment by Tharun24** [comment]
Hi Sarthak, really sorry for the delayed response. The new commit seems to throw segmentation fault. We are doing the following steps:

1) cmake CMakeLists.txt 
2) make 
3) make install . Then ./runme SLIDE/Config_file . 

I'm I missing something? Can you please re-confirm that it works on your end?

Also, the MAPLEN value in Config.h file has to the output layer size in Config.csv file.

**Comment by sarthakpati** [comment]
> Also, the MAPLEN value in Config.h file has to the output layer size in Config.csv file.

I didn't understand what you mean by this. I am not altering any source code..

**Comment by keroro824** [comment]
@sarthakpati We are working on it :). What @Tharun24 was saying is some diagnosis details why we might fail on running the pull request. We will try to merge it by tonight!

**Comment by keroro824** [comment]
@sarthakpati  Thanks for a great job :)!

**Pull request merged**
